### ISSUE TITLE
Clean checkout of kleros repo cannot do lint successfully

### ISSUE THREAD

**Issue by hellwolf** [kleros/kleros-scripts#4]
In master branch of kleros/package.json:

```
    "kleros-scripts": "^0.10.1",
```

When invoking `yarn run lint` these are involved:

```
    "lint:sol": "kleros-scripts lint:sol",
    "lint:js": "kleros-scripts lint:js",
    "lint": "yarn run lint:sol && yarn run lint:js",
```

Close look into the kleros-scripts showing me that:

```
const runCommand = (command, args, { resolveCommand = true } = {}) => {
  const result = spawn.sync(
    //resolveCommand ? resolveBin(command) : command,
```
`resolveBin(command)` gives me `/home/hellwolf/Projects/others/kleros/node_modules/kleros-scripts/node_modules/.bin/solium` and unfortunately that `solium` is not under that directory.

**Comment by epiqueras** [comment]
Did you run “yarn install” after cloning?

**Comment by ferittuncer** [comment]
0.10.1 is not the most up-to-date version, also.

**Comment by hellwolf** [comment]
okay, that was the problem then. I probably did npm install instead.
